project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - products.qmd
    - drinks_kombucha.qmd
    - drinks_tepache.qmd
    - drinks_ginger_beer.qmd
    - drinks_rhubarb.qmd
    - drinks_water_kefir.qmd
    - calculator.qmd
    - about.qmd
    - news/index.qmd
    - news/*.qmd
    - research/index.qmd
    - research/*.qmd
  post-render:
    - touch docs/.nojekyll
  resources:
    - .nojekyll
    - CNAME

website:
  title: "Less Wasted"
  site-url: "https://lesswasted.nl"
  repo-url: "https://github.com/lesswasted/website/"
  favicon: images/logo.png
  twitter-card: true
  page-navigation: false
  search: false   # optional: false makes sense for a 2-page site
  google-analytics:
    tracking-id: "G-35786638"
    anonymize-ip: true
    storage: cookies      # or: none  (see note below)
  cookie-consent:
    type: express         # opt-in; use "implied" for a softer banner
    style: simple

  page-footer:
    background: "#fff8f4"
    center: © 2026 Less Wasted  &middot; Made with {{< fa brands r-project >}} and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) 

  navbar:
    title: false
    logo: images/logo.drawio.png
    logo-alt: "Less Wasted"
    background: "#fff8f4"
    left:
      - href: index.qmd
        text: Home
      - text: Drinks  
        menu:
          - href: products.qmd
            text: All drinks
          - href: drinks_kombucha_gt.qmd
            text: Kombucha G&T
          - href: drinks_tepache.qmd
            text: Tepache
          - href: drinks_ginger_beer.qmd
            text: Boosted Ginger Beer
          - href: drinks_rhubarb.qmd
            text: Rhubarb Fizz
          - href: drinks_water_kefir.qmd
            text: Peely Spicy Lemon Water Kefir
      - href: news/index.qmd
        text: Blog
      - text: BAC Calculator
        href: calculator.qmd
      - href: about.qmd
        text: Who we are  

format:
  html:
    theme:
      - styles/custom.scss
      - yeti
    mainfont: 'Karla'
    toc: false          # no need for TOC on short pages
    link-external-newwindow: true
    smooth-scroll: true
    resources:
      - images