<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-07-02">
<meta name="description" content="Are recycled bottles and cans really that sustainable?">

<title>Bottle and can sustainability – Less Wasted</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<link href="../images/logo.png" rel="icon" type="image/png">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-be74d8cdf67f045810bc6a58d88af17a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<meta name="twitter:title" content="Bottle and can sustainability – Less Wasted">
<meta name="twitter:description" content="Are recycled bottles and cans really that sustainable?">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/logo.drawio.png" alt="Less Wasted" class="navbar-logo light-content">
    <img src="../images/logo.drawio.png" alt="Less Wasted" class="navbar-logo dark-content">
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-drinks" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Drinks</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-drinks">    
        <li>
    <a class="dropdown-item" href="../products.html">
 <span class="dropdown-text">All drinks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../drinks_kombucha_gt.qmd">
 <span class="dropdown-text">Kombucha G&amp;T</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../drinks_tepache.html">
 <span class="dropdown-text">Tepache</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../drinks_ginger_beer.html">
 <span class="dropdown-text">Boosted Ginger Beer</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../drinks_rhubarb.html">
 <span class="dropdown-text">Rhubarb Fizz</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../drinks_water_kefir.html">
 <span class="dropdown-text">Peely Spicy Lemon Water Kefir</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../news/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../calculator.html"> 
<span class="menu-text">BAC Calculator</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">Who we are</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Bottle and can sustainability</h1>
</div>

<div>
  <div class="description">
    Are recycled bottles and cans really that sustainable?
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 2, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Recent statiegeld legislation in Netherlands is a real step forward in encouraging people to</p>
<p>Beer and cider is served in reusable kegs and poured in glasses, meaing there is almost no waste stream. But such large kegs mean trucks are needed to get it to market and businesses need to have lots of space for them.</p>
<p>Plastic bottles can Oxebar have developed</p>
<p>In 2024 it was estimated that</p>
<section id="beverage-packaging-reuse-vs-recycling-annotated-bibliography" class="level1">
<h1>Beverage packaging: reuse vs recycling — annotated bibliography</h1>
<p><em>Scope: energy and carbon intensity of glass, aluminium, PET and steel/PET keg beverage packaging, with an emphasis on reuse-vs-recycling comparisons and the reconditioning (washing) and transport assumptions that drive the results. Compiled for the Less Wasted keg reuse context.</em></p>
<p><strong>How to read this.</strong> Conclusions in this literature hinge almost entirely on three assumptions: the number of reuse cycles a refillable achieves, the reconditioning (washing) inventory, and the return transport distance. Two studies using the same materials can reach opposite conclusions by varying these. The comparison table below extracts those parameters per study so you can see what’s actually driving each headline. Where a source is industry-funded (PET or aluminium trade associations) it is flagged — those reach opposing conclusions from overlapping data and are best treated as bounding cases rather than neutral evidence.</p>
<p><strong>DOI confidence.</strong> DOIs marked ✓ were confirmed from the publisher or an institutional repository. Items given only a ScienceDirect PII or a note should have their DOI verified before formal citation.</p>
<hr>
<section id="parameter-comparison-table" class="level2">
<h2 class="anchored" data-anchor-id="parameter-comparison-table">Parameter comparison table</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Study</th>
<th>Formats compared</th>
<th>Reuse cycles assumed</th>
<th>Reconditioning / washing inventory</th>
<th>Transport assumptions</th>
<th>Headline result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Amienyo et al.&nbsp;2013</td>
<td>Glass 0.75 L, Al can 0.33 L, PET 0.5/2 L (single-use, cradle-to-grave)</td>
<td>Sensitivity: glass reused up to a few times</td>
<td>Not the focus</td>
<td>Includes shipping cans abroad for recycling</td>
<td>Packaging = 59–77% of total impact; glass highest GWP, PET lowest; reusing glass ~3× makes it comparable to single-use PET / cans</td>
</tr>
<tr class="even">
<td>Landi et al.&nbsp;2020</td>
<td>Refillable vs single-use glass (1 L mineral water)</td>
<td>Cites 20–30 rotations; ~30 common in literature</td>
<td>Hot-water + detergent/acid/disinfectant wash</td>
<td>98.69% return rate; ~1.31% loss per delivery; benefits shown ≤250 km</td>
<td>Refillable beer (20 reuses, 250 km): −79% climate, −76% primary energy vs single-use glass</td>
</tr>
<tr class="odd">
<td>Le Féon et al.&nbsp;2024</td>
<td>Reusable vs single-use glass (new beverage)</td>
<td>Modelled per-cycle; 1% rejected at collection</td>
<td><strong>0.5 L water + 0.008 kg soda ash + 0.01 kWh electricity per bottle</strong></td>
<td>19 t lorry to cleaning facility 100 km away</td>
<td>A <em>badly configured</em> returnable system can slightly exceed single-use; 55 parameters; return distance + rotations decisive</td>
</tr>
<tr class="even">
<td>Morgan et al.&nbsp;2022</td>
<td>Single-use glass vs Al can vs reusable glass; steel keg vs PET keg (7 breweries)</td>
<td>Reusable glass pool</td>
<td>Included in reusable-glass scenario</td>
<td>Van distribution a hotspot; lorry sharing cuts impact</td>
<td>Reusable glass or can beat single-use glass; <strong>PET kegs <em>worse</em> than steel kegs at short distance</strong></td>
</tr>
<tr class="odd">
<td>Marrucci et al.&nbsp;2024</td>
<td>PET keg 20 L, glass 0.33 L, Al can 0.33 L (<strong>all one-way</strong>)</td>
<td>None (all non-reusable)</td>
<td>n/a</td>
<td>Sensitivity on load factor + waste distance</td>
<td>One-way PET keg ~90% lower footprint than one-way glass/can (weights: glass ~60.6 kg/hl vs keg 1.5, can 5.5)</td>
</tr>
<tr class="even">
<td>Niero &amp; Olsen 2016</td>
<td>Al can closed-loop (UBC) vs mixed-scrap recycling</td>
<td>n/a (recycling study)</td>
<td>n/a</td>
<td>n/a</td>
<td>Closed-loop can-to-can lower climate impact; alloying elements limit true closed loop</td>
</tr>
<tr class="odd">
<td>ZWE meta-analysis 2020</td>
<td>32 LCAs, all formats</td>
<td>Varies</td>
<td>Varies</td>
<td>Transport = main reusable hotspot</td>
<td>Reusable glass: −85% vs single-use glass, −75% vs single-use PET, −57% vs can; breakeven 2–3 cycles</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="a.-cross-material-foundational-lcas" class="level2">
<h2 class="anchored" data-anchor-id="a.-cross-material-foundational-lcas">A. Cross-material foundational LCAs</h2>
<p><strong>Amienyo, D., Gujba, H., Stichnothe, H. &amp; Azapagic, A. (2013).</strong> Life cycle environmental impacts of carbonated soft drinks. <em>International Journal of Life Cycle Assessment</em>, 18(1), 77–92. DOI: 10.1007/s11367-012-0459-y ✓</p>
<p>The most-cited reference point in the field. Cradle-to-grave, UK context. Establishes that packaging dominates the footprint (59–77% of most impact categories), that single-use glass has the highest GWP and PET the lowest of the three, and — via sensitivity analysis — that reusing glass roughly three times brings it level with single-use PET and aluminium cans. Independent (academic).</p>
<p><strong>Brock, A. &amp; Williams, I. (2020).</strong> Life Cycle Assessment of Beverage Packaging. <em>Detritus</em>, 13, 47–61. (Open access via eprints.soton.ac.uk/447477; verify DOI.)</p>
<p>Broader, more recent comparative ranking across eleven CML impact categories; readable, and useful for the policy framing (single-use taxes as a lever toward reusables). Independent (academic).</p>
</section>
<section id="b.-glass-reuse-vs-recycling-with-reconditioning-inventories" class="level2">
<h2 class="anchored" data-anchor-id="b.-glass-reuse-vs-recycling-with-reconditioning-inventories">B. Glass — reuse vs recycling, with reconditioning inventories</h2>
<p><strong>Landi et al.&nbsp;(2020).</strong> Reusing glass bottles in Italy: A life cycle assessment evaluation. <em>Procedia CIRP</em>, 90, 192–197. DOI: 10.1016/j.procir.2020.01.094 ✓</p>
<p>Your rotation-threshold anchor. Models a real refillable water system (98.69% return rate, ~1.31% loss per delivery) and reviews European evidence that a refillable beer system at 20 reuses over 250 km delivers roughly −79% climate change and −76% primary energy versus single-use glass. Independent (academic).</p>
<p><strong>Le Féon, S., Gésan-Guiziou, G., Yannou-Le Bris, G., Aubin, J. &amp; Pénicaud, C. (2024).</strong> Life cycle assessment based optimization of scenarios of reusable glass bottles using context-specific key parameters. <em>Cleaner Environmental Systems</em>, 2024. ScienceDirect PII S2666789424000631; open access on HAL: hal.inrae.fr/hal-04705714v1 (verify DOI).</p>
<p>The paper to mine for realistic reconditioning numbers. Explicit cleaning inventory of <strong>0.5 L water, 0.008 kg soda ash and 0.01 kWh electricity per bottle</strong>, a 1% reject rate at collection, and a 19 t lorry to a cleaning facility 100 km away, across 55 input parameters. Its key contribution: a poorly configured returnable system can come out <em>slightly worse</em> than single-use, correcting the idealised generic assumptions in older work. Independent (academic).</p>
<p><strong>Van Doorsselaer, K. &amp; Lox, F. (1999).</strong> LCA comparison between recycle and reuse of glass beer bottles. (ResearchGate 302009172; verify DOI.)</p>
<p>Older but foundational for the beer-bottle reuse-vs-recycle question specifically; models different reuse percentages across the full chain (washing, filling, pasteurising, wastewater). Independent (academic).</p>
</section>
<section id="c.-aluminium-and-pet" class="level2">
<h2 class="anchored" data-anchor-id="c.-aluminium-and-pet">C. Aluminium and PET</h2>
<p><strong>Niero, M. &amp; Olsen, S.I. (2016).</strong> Circular economy: To be or not to be in a closed product loop? A LCA of aluminium cans with inclusion of alloying elements. <em>Resources, Conservation &amp; Recycling</em>. ScienceDirect PII S0921344916301604 (verify DOI).</p>
<p>Explains why the ~5%-of-primary-energy remelting figure for aluminium doesn’t fully close the loop: alloying elements and collection losses mean primary metal keeps entering. Closed-loop can-to-can beats mixed-scrap recycling. Independent (academic).</p>
<p><strong>Tamburini et al.&nbsp;(2021).</strong> Plastic (PET) vs bioplastic (PLA) or refillable aluminium bottles — what is the most sustainable choice for drinking water? A life-cycle analysis. <em>Environmental Research</em>, 2021. ScienceDirect PII S0013935121002681 (verify DOI).</p>
<p>Key for the reusable-vs-single-use logic: a single PET bottle has the lowest <em>production</em> impact of any material, but over a year of use the single-use PET footprint balloons while a refillable’s per-year production impact becomes negligible regardless of material — washing method then dominates. Independent (academic).</p>
<p><strong>NAPCOR / Franklin Associates (2023).</strong> PET Life Cycle Assessment Report. napcor.com/pet-life-cycle-assessment-report-2023.</p>
<p>Finds single-use PET better than cans and glass for CSDs and still water (US). <strong>Industry-funded (PET trade association)</strong> — bounding case, not neutral.</p>
<p><strong>The Aluminum Association / John Beath Environmental (2023).</strong> Aluminum Cans Leading the Way to Limit Carbon Impact. aluminum.org.</p>
<p>Meta-review putting cans similar to PET and better than glass; reports GWP ranges of 0.11–0.51 (Al can), 0.39–1.05 (glass), 0.11–0.65 (PET) kg CO₂e/L. <strong>Industry-funded (aluminium)</strong> — bounding case in the opposite direction.</p>
</section>
<section id="d.-kegs-and-brewery-specific-most-relevant-to-less-wasted" class="level2">
<h2 class="anchored" data-anchor-id="d.-kegs-and-brewery-specific-most-relevant-to-less-wasted">D. Kegs and brewery-specific (most relevant to Less Wasted)</h2>
<p><strong>Morgan, D.R., Styles, D. &amp; Lane, E.T. (2022).</strong> Packaging choice and coordinated distribution logistics to reduce the environmental footprint of small-scale beer value chains. <em>Journal of Environmental Management</em>, 307, 114591. DOI: 10.1016/j.jenvman.2022.114591 ✓ (open access, CC licence)</p>
<p>The single most on-point paper for you. LCA of seven micro-breweries (footprints 727–1336 g CO₂e/L). Switching single-use glass to reusable glass or cans cut Brewery E’s footprint ~27% each; reusable glass was best for four of seven breweries. Critically: <strong>replacing steel kegs with PET kegs <em>increases</em> footprints for short-distance delivery</strong>, with savings only in long-distance van scenarios — direct support for keeping a reusable steel keg loop in a short-radius network. Independent (academic), open access.</p>
<p><strong>Marrucci, L. et al.&nbsp;(2024).</strong> Identifying the most sustainable beer packaging through a Life Cycle Assessment. <em>Science of the Total Environment</em>, 948, 174941. DOI: 10.1016/j.scitotenv.2024.174941 ✓</p>
<p>Apparent counterpoint to Morgan — finds draught beer in PET kegs ~90% lower footprint than other formats — but note the crucial caveat that <strong>all formats in this study are one-way / non-reusable</strong>, so it compares a one-way PET keg to one-way glass and cans, not to a reusable steel keg. Its packaging weights (glass ~60.6 kg/hl vs PET keg 1.5, can 5.5) neatly quantify the glass transport penalty. Independent (academic).</p>
<p><strong>From Circular to Linear? Assessing the Life Cycle Environmental and Economic Sustainability of Steel and Plastic Beer Kegs (2022).</strong> <em>Circular Economy and Sustainability</em> (Springer). DOI: 10.1007/s43615-021-00142-w ✓</p>
<p>Covers both environmental and cost sides of the steel-vs-plastic keg choice, and notes plastic kegs improve markedly where a local closed-loop PET recycling route exists. Independent (academic).</p>
</section>
<section id="e.-reviews-meta-analysis-and-dutch-context" class="level2">
<h2 class="anchored" data-anchor-id="e.-reviews-meta-analysis-and-dutch-context">E. Reviews, meta-analysis and Dutch context</h2>
<p><strong>LCA of reusable food and beverage packaging systems: a proposal of good practice (2025).</strong> <em>Journal of Cleaner Production</em>. ScienceDirect PII S0959652625005578 (verify DOI).</p>
<p>Methodological guide: identifies number of reuse cycles and reconditioning configuration (washing, refilling, return logistics) as the two central parameters. Use this to decide which assumptions to defend in your own model. Independent (academic).</p>
<p><strong>Zero Waste Europe / Reloop (2020).</strong> <em>Reusable vs single-use packaging: a review of environmental impacts</em> (synthesis of 32 LCAs).</p>
<p>Aggregate figures: reusable glass −85% vs single-use glass, −75% vs single-use PET, −57% vs cans; breakeven after 2–3 reuse cycles; transport the dominant reusable hotspot. <strong>Advocacy-commissioned grey literature</strong> — but aggregates peer-reviewed inputs and its breakeven figure aligns with the academic work.</p>
<p><strong>CE Delft (2018/2021).</strong> LCA: recycling of household plastic packaging waste. ce.nl/en/publications/1208.</p>
<p>Dutch policy-grade grey literature (not journal peer-review, but ISO-consistent and the standard NL reference). Concludes that at-source and post-consumer plastic separation plus a deposit on large PET all beat incineration environmentally. CE Delft’s publications library is the place to look for Dutch deposit-return and reuse-system inventories.</p>
<p><strong>Dutch context sources (authoritative-for-NL, not peer-reviewed):</strong> Milieu Centraal — packaging glass at 60% recycled content saves only ~15% energy vs new glass, because remelting cullet still needs ~1,300 °C; washing a bottle uses ~600 mL water vs ~2 L to make a new one (Transitieagenda Consumptiegoederen / Mission Reuse pilot). The Dutch reuse loop in practice is essentially the shared beer bottle (Bruine Nederlandse Retourfles), refilled up to ~40× over ~8 years; most other consumer glass goes via the glasbak and is melted, not washed and refilled.</p>
<hr>
</section>
<section id="bottom-line-for-the-keg-model" class="level2">
<h2 class="anchored" data-anchor-id="bottom-line-for-the-keg-model">Bottom line for the keg model</h2>
<p>The peer-reviewed weight of evidence supports a reusable steel keg in a short-radius local loop over both single-use anything and one-way PET kegs (Morgan et al.&nbsp;2022 is explicit on the steel-vs-PET-keg point at short distance). The single-use-vs-refillable split matters more than the material: once a refillable clears its rotation threshold (breakeven ~2–3 cycles for glass per ZWE; kegs far exceed this), the container material stops driving the result and washing energy plus return distance take over (Le Féon et al.&nbsp;2024; Tamburini et al.&nbsp;2021). Those two variables — washing inventory and collection radius — are the only ones that could erode a keg loop’s advantage, and both are favourable for a tight local café network.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/lesswasted\.nl");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Less Wasted · Made with <i class="fa-brands fa-r-project" aria-label="r-project"></i> and <a href="https://quarto.org/"><img src="https://quarto.org/quarto.png" class="img-fluid" alt="Quarto" width="65"></a></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>